# Fonts
font_size 16
font_family family="Maple Mono NF CN"
bold_font auto
italic_font auto
bold_italic_font auto
modify_font cell_width 100%
modify_font cell_height 100%
font_features MapleMono-NF-CN-Regular +cv01 +calt
font_features MapleMono-NF-CN-Light +cv01 +calt
font_features MapleMono-NF-CN-SemiBold +cv01 +calt
font_features MapleMono-NF-CN-Italic +cv01 +calt
font_features MapleMono-NF-CN-SemiBoldItalic +cv01 +calt

# Window layout
hide_window_decorations yes
window_padding_width 15
background_opacity 0.8
background_blur 30
remember_window_size yes

# Tab bar
tab_bar_edge top

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
