# Fonts
font_size 16
font_family family="Maple Mono NF CN"
font_features MapleMono-NF-CN-Regular -calt +cv01 +cv04
font_features MapleMono-NF-CN-SemiBold -calt +cv01 +cv04
font_features MapleMono-NF-CN-Italic -calt +cv01 +cv04
font_features MapleMono-NF-CN-SemiBoldItalic -calt +cv01 +cv04

# Window layout
window_padding_width 0 10
hide_window_decorations titlebar-only

# Tab bar
tab_bar_edge top

# Color scheme
include current-theme.conf
